import type { CategorySlug, CollectionSlug, Colorway, Dept, Product, Review, SizeSystem, Variant } from "@/lib/commerce/types";
import { reviewPool } from "./reviews";
import { productImageMeta } from "./image-meta";

/*
 * The Ordova catalog (fictional). 36 pieces across 7 categories.
 *
 * Products are declared compactly below and expanded into full `Product`
 * objects (variants with per-size stock, SKUs, reviews) by `build()`.
 * Stock is deterministic (hashed from the SKU) plus explicit overrides, so
 * every build renders the same "Only 1 left" and sold-out states.
 */

const SIZES: Record<string, string[]> = {
  alpha: ["XS", "S", "M", "L", "XL"],
  waist: ["28", "30", "32", "34", "36", "38"],
  wwaist: ["24", "26", "28", "30", "32"],
  hat: ["S/M", "L/XL"],
  belt: ["S", "M", "L"],
  one: ["One size"],
};

const CARE = {
  linen: ["Machine wash cold on a gentle cycle", "Line dry in the shade", "Warm iron while slightly damp"],
  cotton: ["Machine wash cold with like colours", "Line dry or tumble dry low", "Warm iron"],
  wool: ["Dry clean, or hand wash cold with wool soap", "Dry flat away from heat", "Steam to refresh — no direct iron"],
  silk: ["Dry clean, or hand wash cold", "Don't wring — roll in a towel", "Cool iron on the reverse"],
  denim: ["Wash inside out, cold, as rarely as you can", "Line dry", "Expect the indigo to fade with wear"],
  knit: ["Hand wash cold with wool soap", "Dry flat and reshape while damp", "Fold, never hang"],
  leather: ["Wipe with a soft dry cloth", "Condition twice a year", "Store stuffed, in the dust bag"],
  suede: ["Brush with a suede brush", "Spot clean only; professional clean once a season", "Keep out of the rain"],
  felt: ["Brush with a soft brush, counter-clockwise", "Handle by the brim, not the crown", "Store crown-down on a flat surface"],
} as const;

type Def = {
  slug: string;
  name: string;
  dept: Dept;
  category: CategorySlug;
  price: number;
  compareAt?: number;
  sizes: keyof typeof SIZES;
  /** [name, hex, optional price override, which photo shows this colour ("c2" = its own hero, "2" = the alternate shot)] */
  colors: [string, string, number?, ("c2" | "2")?][];
  alts: [string, string];
  short: string;
  long: string;
  details: string[];
  materials: string;
  fabric: string;
  care: keyof typeof CARE;
  fit: Product["fit"];
  fitScore?: number;
  model?: string;
  origin?: string;
  rating: number;
  reviewCount: number;
  collections?: CollectionSlug[];
  isNew?: boolean;
  isBestseller?: boolean;
  featured: number;
  dropped: string;
  pairs: string[];
  /** size → stock for the first colour ("*" = every size of every colour) */
  stock?: Record<string, number>;
  focal?: [string?, string?];
};

const W = "Model is 5'10\" and wears S";
const M = "Model is 6'1\" and wears M";
const DALLAS = "Cut and sewn in our Dallas studio";

const defs: Def[] = [
  // ─── Women · dresses ───────────────────────────────────────────────
  {
    slug: "calle-slip-dress",
    name: "Calle Slip Dress",
    dept: "women",
    category: "dresses",
    price: 248,
    sizes: "alpha",
    colors: [["Ivory", "#ece3d0"], ["Black", "#1b1a1a", 248, "c2"]],
    alts: ["Bias-cut satin slip dress on a model against a plain studio wall", "Slip dress in motion, back view showing the low scoop"],
    short: "A bias-cut midi slip in sand-washed satin that moves like water.",
    long: "Cut on the bias so it falls close without clinging, with adjustable straps and a low scoop at the back. Sand-washed so the satin reads matte in daylight and glows at night. We cut each one by hand — the bias doesn't forgive shortcuts.",
    details: ["Bias cut, midi length (47\" from strap)", "Adjustable straps", "Low scoop back", "French seams throughout"],
    materials: "100% sand-washed viscose satin",
    fabric: "Satin",
    care: "silk",
    fit: "Regular",
    model: W,
    origin: DALLAS,
    rating: 4.9,
    reviewCount: 64,
    collections: ["new-in", "bestsellers", "weekend-edit"],
    isNew: true,
    isBestseller: true,
    featured: 100,
    dropped: "2026-09-26",
    pairs: ["mesa-cropped-jacket", "ring-crossbody", "silk-square-scarf"],
    stock: { M: 1 },
  },
  {
    slug: "marfa-shirt-dress",
    name: "Marfa Linen Dress",
    dept: "women",
    category: "dresses",
    price: 198,
    sizes: "alpha",
    colors: [["Khaki", "#8f8a6a"]],
    alts: ["Linen shirt dress with a tie waist on a model against a white wall", "Close view of the linen shirt dress buttons and tie belt"],
    short: "A washed-linen dress with a dropped waist and a full skirt — the desert-road dress.",
    long: "Named for the town that taught Texas how to be minimal. Heavy European linen, garment-washed until it's soft from the first wear, with three-quarter sleeves, a dropped waist seam, deep side pockets and a skirt that moves in the wind.",
    details: ["Relaxed fit, midi length", "Dropped waist, gathered skirt", "Deep side-seam pockets", "Corozo buttons at the back neck"],
    materials: "100% European linen, garment-washed",
    fabric: "Linen",
    care: "linen",
    fit: "Relaxed",
    model: W,
    origin: DALLAS,
    rating: 4.8,
    reviewCount: 41,
    collections: ["weekend-edit", "essentials"],
    isBestseller: true,
    featured: 92,
    dropped: "2026-05-02",
    pairs: ["woven-belt", "market-canvas-tote", "felt-rancher-hat"],
  },
  {
    slug: "trinity-knit-dress",
    name: "Trinity Rib Dress",
    dept: "women",
    category: "dresses",
    price: 159,
    compareAt: 228,
    sizes: "alpha",
    colors: [["Camel", "#b8926a"]],
    alts: ["Ribbed knit midi dress on a model, full length", "Ribbed knit dress detail showing the rib texture"],
    short: "A ribbed knit midi that holds its line from bar to boardroom.",
    long: "Knitted in a dense 2×2 rib that recovers its shape after every wear. Long sleeves, a crew neck and a slit at the back hem so you can actually walk. From last winter's run — the final sizes are in the Archive Sale.",
    details: ["Close fit, midi length", "Back hem slit", "Fully fashioned, linked seams"],
    materials: "70% merino wool, 30% recycled nylon",
    fabric: "Knit",
    care: "knit",
    fit: "Slim",
    model: W,
    origin: "Knitted in Los Angeles, finished in Dallas",
    rating: 4.7,
    reviewCount: 28,
    collections: ["archive-sale"],
    featured: 70,
    dropped: "2025-11-12",
    pairs: ["pecan-wool-coat", "plinth-leather-tote", "bridle-belt"],
    stock: { XS: 0, S: 2, M: 1, L: 0, XL: 0 },
  },
  // ─── Women · tops ──────────────────────────────────────────────────
  {
    slug: "bishop-poplin-shirt",
    name: "Bishop Poplin Shirt",
    dept: "women",
    category: "tops",
    price: 128,
    sizes: "alpha",
    colors: [["White", "#f4f2ee"]],
    alts: ["Oversized white poplin shirt on a model against a studio wall", "Poplin shirt worn open over a tank, detail of collar"],
    short: "The oversized poplin shirt we'd keep if we could keep one thing.",
    long: "Crisp two-ply cotton poplin, cut generously through the body with a dropped shoulder and a long curved hem that tucks or doesn't. The collar has a light fused stand so it stays up on its own.",
    details: ["Oversized fit, dropped shoulder", "Curved hem, longer at the back", "Box-pleat back yoke", "Mother-of-pearl buttons"],
    materials: "100% two-ply cotton poplin",
    fabric: "Cotton",
    care: "cotton",
    fit: "Oversized",
    fitScore: 0.4,
    model: W,
    origin: DALLAS,
    rating: 4.9,
    reviewCount: 88,
    collections: ["bestsellers", "essentials", "workwear"],
    isBestseller: true,
    featured: 96,
    dropped: "2026-02-18",
    pairs: ["oak-cliff-wide-trouser", "bridle-belt", "plinth-leather-tote"],
  },
  {
    slug: "elm-rib-tank",
    name: "Elm Rib Tank",
    dept: "women",
    category: "tops",
    price: 48,
    sizes: "alpha",
    colors: [["Sage", "#9fae92"], ["White", "#f2f0ea", 48, "c2"]],
    alts: ["Fitted ribbed tank top on a model, cropped torso view", "Ribbed tank top detail, close crop"],
    short: "A close-fitting rib tank with a high neck and real recovery.",
    long: "The layer under everything. A fine cotton rib with a touch of elastane so it snaps back, a higher scoop that sits under a shirt, and bound edges that won't roll after washing.",
    details: ["Close fit", "High scoop neck", "Bound edges"],
    materials: "95% organic cotton, 5% elastane",
    fabric: "Cotton",
    care: "cotton",
    fit: "Slim",
    model: W,
    origin: DALLAS,
    rating: 4.8,
    reviewCount: 120,
    collections: ["essentials", "gifts-under-100", "bestsellers"],
    isBestseller: true,
    featured: 80,
    dropped: "2026-03-10",
    pairs: ["ellum-barrel-jean", "bishop-poplin-shirt", "washed-cap"],
  },
  {
    slug: "lamar-boxy-tee",
    name: "Lamar Boxy Tee",
    dept: "women",
    category: "tops",
    price: 58,
    sizes: "alpha",
    colors: [["White", "#f4f2ee"], ["Black", "#1a1a18", 58, "c2"]],
    alts: ["Boxy heavyweight white tee on a model against a white backdrop", "Boxy tee worn tucked into wide trousers"],
    short: "A 240-gram boxy tee with a cropped body and a sturdy collar.",
    long: "Heavyweight jersey that hangs instead of clinging, cut wide and slightly cropped to sit at the high hip. The rib collar is narrow and stitched flat so it won't bacon after a summer of washing.",
    details: ["Boxy, slightly cropped", "240 gsm jersey", "Narrow flat-stitched collar"],
    materials: "100% organic cotton jersey",
    fabric: "Cotton",
    care: "cotton",
    fit: "Oversized",
    fitScore: 0.5,
    model: W,
    origin: DALLAS,
    rating: 4.7,
    reviewCount: 96,
    collections: ["essentials", "gifts-under-100", "weekend-edit"],
    featured: 74,
    dropped: "2026-03-10",
    pairs: ["caliche-pleated-trouser", "bucket-hat", "market-canvas-tote"],
  },
  // ─── Women · trousers ──────────────────────────────────────────────
  {
    slug: "oak-cliff-wide-trouser",
    name: "Oak Cliff Wide Trouser",
    dept: "women",
    category: "trousers",
    price: 168,
    sizes: "alpha",
    colors: [["Stone", "#cfc6b6"], ["Black", "#1b1b19", 168, "2"]],
    alts: ["High-waisted wide-leg black trousers on a model, full length", "Wide-leg trouser in motion from the side"],
    short: "High-rise, wide through the leg, and cut to pool just right over a flat.",
    long: "Our best-selling trouser, named for the neighbourhood we cut it in. A high rise with a hook-and-bar waistband, double front pleats and a full wide leg in a dry, drapey wool-blend twill that doesn't crease on the drive in.",
    details: ["High rise, 31\" inseam (free hem in store)", "Double front pleats", "Side-slant pockets, back welt pockets", "Hook-and-bar closure"],
    materials: "62% wool, 38% polyester twill",
    fabric: "Wool",
    care: "wool",
    fit: "Relaxed",
    model: W,
    origin: DALLAS,
    rating: 4.9,
    reviewCount: 143,
    collections: ["bestsellers", "workwear", "essentials"],
    isBestseller: true,
    featured: 98,
    dropped: "2026-01-20",
    pairs: ["bishop-poplin-shirt", "lone-star-trench", "bridle-belt"],
    stock: { M: 1 },
  },
  {
    slug: "ellum-barrel-jean",
    name: "Ellum High-Rise Jean",
    dept: "women",
    category: "trousers",
    price: 148,
    sizes: "wwaist",
    colors: [["Dark indigo", "#26314a"]],
    alts: ["Light-wash barrel-leg jeans on a model with white sneakers", "Barrel jeans back view showing the yoke and pockets"],
    short: "A high-rise, long-leg jean in deep indigo with a soft kick at the hem.",
    long: "Sits at the natural waist and falls long and straight to a gentle kick that covers the top of a boot. 13.5 oz rigid cotton denim that breaks in to you — expect it to give about half a size in the first month.",
    details: ["High rise, 32\" inseam (free hem in store)", "Straight leg with a soft kick", "Five pockets, button fly"],
    materials: "100% cotton rigid denim, 13.5 oz",
    fabric: "Denim",
    care: "denim",
    fit: "Relaxed",
    fitScore: -0.3,
    model: "Model is 5'9\" and wears 26",
    origin: DALLAS,
    rating: 4.6,
    reviewCount: 57,
    collections: ["new-in", "weekend-edit"],
    isNew: true,
    featured: 88,
    dropped: "2026-09-12",
    pairs: ["lamar-boxy-tee", "woven-belt", "ring-crossbody"],
  },
  {
    slug: "caliche-pleated-trouser",
    name: "Caliche Pleated Trouser",
    dept: "women",
    category: "trousers",
    price: 124,
    compareAt: 178,
    sizes: "alpha",
    colors: [["Charcoal", "#4a4946"]],
    alts: ["Pleated tailored trousers on a model against a pale wall", "Pleated trouser detail showing pleats and waistband"],
    short: "A single-pleat tapered trouser in a dry tropical wool.",
    long: "From the first Caliche collection: a softly tapered leg with a single deep pleat, a slightly dropped rise and a clean waistband with an extended tab. The last sizes are in the Archive Sale.",
    details: ["Mid rise, tapered leg", "Single deep pleat", "Extended tab waistband"],
    materials: "100% tropical wool",
    fabric: "Wool",
    care: "wool",
    fit: "Regular",
    model: W,
    origin: DALLAS,
    rating: 4.7,
    reviewCount: 33,
    collections: ["archive-sale", "workwear"],
    featured: 66,
    dropped: "2025-09-30",
    pairs: ["lamar-boxy-tee", "mesa-cropped-jacket", "plinth-leather-tote"],
    stock: { XS: 1, S: 0, M: 2, L: 0, XL: 1 },
  },
  // ─── Women · outerwear ─────────────────────────────────────────────
  {
    slug: "lone-star-trench",
    name: "Lone Star Trench",
    dept: "women",
    category: "outerwear",
    price: 398,
    sizes: "alpha",
    colors: [["Beige", "#c9b28c"], ["Olive", "#5b5d3e", 398, "c2"]],
    alts: ["Classic khaki trench coat on a model against a studio wall", "Trench coat worn open, walking, belt swinging"],
    short: "A double-breasted trench in water-repellent cotton gabardine, cut for Texas weather.",
    long: "Light enough for a 60-degree morning, sharp enough for a 90-degree meeting with the AC on. Storm flap, raglan sleeves, a throat latch you'll actually use, and a cupro-lined body so it slides over knits.",
    details: ["Relaxed fit, below-knee length", "Double-breasted with horn buttons", "Removable belt, cuff straps", "Cupro lining"],
    materials: "100% cotton gabardine with a PFC-free water-repellent finish",
    fabric: "Cotton",
    care: "cotton",
    fit: "Relaxed",
    model: W,
    origin: DALLAS,
    rating: 4.9,
    reviewCount: 52,
    collections: ["new-in", "bestsellers", "workwear"],
    isNew: true,
    isBestseller: true,
    featured: 99,
    dropped: "2026-09-26",
    pairs: ["oak-cliff-wide-trouser", "bishop-poplin-shirt", "plinth-leather-tote"],
  },
  {
    slug: "pecan-wool-coat",
    name: "Pecan Wool Coat",
    dept: "women",
    category: "outerwear",
    price: 480,
    sizes: "alpha",
    colors: [["Camel", "#b17d55"], ["Black", "#1c1b1a", 498, "c2"]],
    alts: ["Long camel wool coat on a model, full length", "Wool coat collar and lapel close-up"],
    short: "A long, softly tailored coat in double-faced wool. Our heirloom piece.",
    long: "Double-faced wool means no lining and no bulk — every edge is hand-finished by folding the two faces into each other, which takes our seamstress a full day per coat. We make thirty a season. The black is cut from a heavier Italian melton, hence the small difference in price.",
    details: ["Relaxed fit, mid-calf length", "Hand-finished double-faced construction", "Notch lapel, patch pockets", "Made in a run of 30"],
    materials: "90% wool, 10% cashmere, double-faced",
    fabric: "Wool",
    care: "wool",
    fit: "Relaxed",
    model: W,
    origin: DALLAS,
    rating: 5,
    reviewCount: 19,
    collections: ["new-in"],
    isNew: true,
    featured: 97,
    dropped: "2026-10-01",
    pairs: ["trinity-knit-dress", "mohair-scarf", "plinth-leather-tote"],
    stock: { XS: 2, S: 1, M: 3, L: 1, XL: 0 },
  },
  {
    slug: "mesa-cropped-jacket",
    name: "Mesa Boxy Blazer",
    dept: "women",
    category: "outerwear",
    price: 188,
    compareAt: 268,
    sizes: "alpha",
    colors: [["Black", "#1b1b19"], ["Sage", "#b9c4a5", 188, "c2"]],
    alts: ["Cropped boxy jacket on a model against a light backdrop", "Cropped jacket detail showing collar and button"],
    short: "An unstructured, boxy blazer in brushed cotton twill — sharp over denim, easy over a slip.",
    long: "Square through the body with a dropped shoulder, soft notch lapels and no shoulder pads, so it wears like a shirt. Made from last season's brushed twill — the remaining sizes are in the Archive Sale.",
    details: ["Boxy, hip length", "Unstructured, half-lined", "Two flap pockets"],
    materials: "100% brushed cotton twill",
    fabric: "Cotton",
    care: "cotton",
    fit: "Relaxed",
    model: W,
    origin: DALLAS,
    rating: 4.6,
    reviewCount: 22,
    collections: ["archive-sale"],
    featured: 64,
    dropped: "2025-10-14",
    pairs: ["calle-slip-dress", "oak-cliff-wide-trouser", "ring-crossbody"],
    stock: { XS: 0, S: 1, M: 0, L: 2, XL: 0 },
  },
  // ─── Men · tops ────────────────────────────────────────────────────
  {
    slug: "ervay-oxford",
    name: "Ervay Oxford Shirt",
    dept: "men",
    category: "tops",
    price: 118,
    sizes: "alpha",
    colors: [["Ecru", "#ece6d6"], ["Light blue", "#a9c0da", 118, "c2"]],
    alts: ["Button-down oxford shirt on a model against a plain wall", "Oxford shirt collar and button detail"],
    short: "A soft-roll button-down in heavy oxford cloth that only gets better.",
    long: "The collar rolls instead of lying flat — the way an oxford should. Heavy 2×1 oxford cloth, a locker loop, a box pleat and a single chest pocket. Wear it with a tie on Monday and cuffed with chinos on Saturday.",
    details: ["Regular fit", "Unlined button-down collar with a soft roll", "Back box pleat and locker loop"],
    materials: "100% cotton oxford cloth",
    fabric: "Cotton",
    care: "cotton",
    fit: "Regular",
    model: M,
    origin: DALLAS,
    rating: 4.8,
    reviewCount: 76,
    collections: ["essentials", "workwear", "bestsellers"],
    isBestseller: true,
    featured: 90,
    dropped: "2026-02-18",
    pairs: ["main-street-chino", "field-merino-crew", "bridle-belt"],
  },
  {
    slug: "commerce-camp-shirt",
    name: "Commerce Camp Shirt",
    dept: "men",
    category: "tops",
    price: 76,
    compareAt: 108,
    sizes: "alpha",
    colors: [["Cream", "#ece4d2"], ["Navy", "#2b3442", 76, "c2"]],
    alts: ["Short-sleeve camp collar shirt on a model, relaxed fit", "Camp shirt in motion, open collar detail"],
    short: "A boxy camp-collar shirt in slubby cotton-linen for long Texas summers.",
    long: "Straight hem, open camp collar, and a cut that lets air through. From the summer run — final sizes in the Archive Sale.",
    details: ["Boxy fit, straight hem", "Open camp collar", "Side vents"],
    materials: "55% linen, 45% cotton",
    fabric: "Linen",
    care: "linen",
    fit: "Relaxed",
    model: M,
    origin: DALLAS,
    rating: 4.7,
    reviewCount: 39,
    collections: ["archive-sale", "weekend-edit", "gifts-under-100"],
    featured: 62,
    dropped: "2026-04-22",
    pairs: ["drill-work-trouser", "bucket-hat", "market-canvas-tote"],
    stock: { XS: 0, S: 1, M: 0, L: 1, XL: 2 },
  },
  {
    slug: "akard-overshirt",
    name: "Akard Overshirt",
    dept: "men",
    category: "tops",
    price: 158,
    sizes: "alpha",
    colors: [["Ecru", "#e3dac6"], ["Forest", "#33473a", 158, "c2"]],
    alts: ["Twill overshirt on a model worn open over a tee", "Overshirt pocket and button detail"],
    short: "A heavy twill overshirt — a shirt in July, a jacket in November.",
    long: "Cut from 12 oz cotton twill with a clean point collar, two flap chest pockets and hand-warmer pockets hidden in the side seams. Roomy enough to layer over a knit, sharp enough to wear buttoned on its own.",
    details: ["Regular fit, layers over knits", "Two flap chest pockets", "Hidden side hand-warmer pockets"],
    materials: "100% cotton twill, 12 oz",
    fabric: "Cotton",
    care: "cotton",
    fit: "Regular",
    model: M,
    origin: DALLAS,
    rating: 4.9,
    reviewCount: 61,
    collections: ["new-in", "workwear", "bestsellers"],
    isNew: true,
    isBestseller: true,
    featured: 94,
    dropped: "2026-09-19",
    pairs: ["selvedge-straight-jean", "rib-beanie", "depot-weekender"],
  },
  // ─── Men · knitwear ────────────────────────────────────────────────
  {
    slug: "field-merino-crew",
    name: "Field Merino Crew",
    dept: "men",
    category: "knitwear",
    price: 148,
    sizes: "alpha",
    colors: [["Cream", "#ece4d2"], ["Black", "#1a1a18", 148, "c2"]],
    alts: ["Fine merino crewneck sweater on a model against a plain backdrop", "Merino knit texture close-up at the cuff"],
    short: "A fine-gauge merino crew that layers under everything and itches under nothing.",
    long: "Extra-fine 17.5-micron merino knitted at 14 gauge, light enough for a Dallas October and warm enough under a coat in January. Saddle shoulders so it sits right under tailoring.",
    details: ["Regular fit", "14-gauge extra-fine knit", "Saddle shoulders"],
    materials: "100% extra-fine merino wool",
    fabric: "Knit",
    care: "knit",
    fit: "Regular",
    model: M,
    origin: "Knitted in Los Angeles, finished in Dallas",
    rating: 4.8,
    reviewCount: 70,
    collections: ["essentials", "workwear"],
    featured: 84,
    dropped: "2026-09-05",
    pairs: ["ervay-oxford", "main-street-chino", "mac-coat"],
  },
  {
    slug: "hollow-cardigan",
    name: "Hollow Cardigan",
    dept: "men",
    category: "knitwear",
    price: 124,
    compareAt: 178,
    sizes: "alpha",
    colors: [["Camel", "#b38d66"], ["Charcoal", "#3a3936", 124, "c2"]],
    alts: ["Chunky knit cardigan on a model worn open", "Chunky cardigan knit and button detail"],
    short: "A deep-V lambswool cardigan with horn buttons. Weekend armour.",
    long: "Knitted in a heavy lambswool blend with a deep V and five horn buttons. Slightly dropped shoulder, generous body. From last winter — final sizes in the Archive Sale.",
    details: ["Relaxed fit", "Five horn buttons", "Two patch pockets"],
    materials: "80% lambswool, 20% nylon",
    fabric: "Knit",
    care: "knit",
    fit: "Relaxed",
    fitScore: 0.3,
    model: M,
    origin: "Knitted in Los Angeles, finished in Dallas",
    rating: 4.7,
    reviewCount: 26,
    collections: ["archive-sale", "weekend-edit"],
    featured: 60,
    dropped: "2025-11-12",
    pairs: ["drill-work-trouser", "rib-beanie", "akard-overshirt"],
    stock: { XS: 0, S: 0, M: 1, L: 1, XL: 0 },
  },
  {
    slug: "fisherman-knit",
    name: "Fisherman Knit",
    dept: "men",
    category: "knitwear",
    price: 198,
    sizes: "alpha",
    colors: [["Cream", "#ece4d2"], ["Rust", "#a4552e", 198, "c2"]],
    alts: ["Cream cable-knit fisherman sweater on a model", "Cable knit texture close-up"],
    short: "A heavy cable crew in undyed wool. The sweater you'll hand down.",
    long: "Undyed natural wool, a classic cable and moss-stitch pattern, and a high crew neck. Heavy enough to replace a jacket on most Dallas winter days.",
    details: ["Relaxed fit", "Undyed natural wool", "Cable and moss stitch"],
    materials: "100% undyed wool",
    fabric: "Knit",
    care: "knit",
    fit: "Relaxed",
    model: M,
    origin: "Knitted in Los Angeles, finished in Dallas",
    rating: 4.9,
    reviewCount: 44,
    collections: ["new-in", "weekend-edit"],
    isNew: true,
    featured: 86,
    dropped: "2026-09-26",
    pairs: ["selvedge-straight-jean", "chore-jacket", "rib-beanie"],
  },
  // ─── Men · trousers ────────────────────────────────────────────────
  {
    slug: "main-street-chino",
    name: "Main Street Chino",
    dept: "men",
    category: "trousers",
    price: 138,
    sizes: "waist",
    colors: [["Tan", "#c2a27a"], ["Olive", "#545741", 138, "c2"]],
    alts: ["Pleated chino trousers on a model with a tucked shirt", "Chino trouser detail at the waistband and pleat"],
    short: "A single-pleat chino with a tapered leg and a little room in the seat.",
    long: "Heavy cotton drill, garment-dyed, with one forward pleat and a gentle taper to a 7.5\" hem. Sits at the natural waist so a tucked shirt stays tucked.",
    details: ["Mid rise, tapered leg", "Single forward pleat", "Unfinished hem — free hem in store"],
    materials: "100% cotton drill, garment-dyed",
    fabric: "Cotton",
    care: "cotton",
    fit: "Regular",
    model: "Model is 6'1\" and wears 32",
    origin: DALLAS,
    rating: 4.8,
    reviewCount: 81,
    collections: ["essentials", "workwear"],
    featured: 82,
    dropped: "2026-02-18",
    pairs: ["ervay-oxford", "field-merino-crew", "bridle-belt"],
  },
  {
    slug: "selvedge-straight-jean",
    name: "Selvedge Straight Jean",
    dept: "men",
    category: "trousers",
    price: 168,
    sizes: "waist",
    colors: [["Raw indigo", "#232b3d"]],
    alts: ["Dark raw selvedge straight jeans on a model", "Selvedge denim cuff showing the self-edge"],
    short: "A straight-leg jean in 14 oz raw selvedge denim. Yours to fade.",
    long: "Unwashed, unsanforized selvedge from a narrow shuttle loom, cut straight with a mid rise. It will shrink about an inch in length on the first soak — the size guide has the details.",
    details: ["Mid rise, straight leg", "Selvedge outseam — cuff it to show", "Copper rivets, button fly"],
    materials: "100% cotton raw selvedge denim, 14 oz",
    fabric: "Denim",
    care: "denim",
    fit: "Regular",
    model: "Model is 6'1\" and wears 32",
    origin: DALLAS,
    rating: 4.9,
    reviewCount: 102,
    collections: ["bestsellers", "essentials"],
    isBestseller: true,
    featured: 91,
    dropped: "2026-01-08",
    pairs: ["akard-overshirt", "fisherman-knit", "bridle-belt"],
    stock: { "32": 1 },
  },
  {
    slug: "drill-work-trouser",
    name: "Drill Work Trouser",
    dept: "men",
    category: "trousers",
    price: 89,
    compareAt: 128,
    sizes: "waist",
    colors: [["Loden", "#5a5240"]],
    alts: ["Relaxed work trousers on a model with boots", "Work trouser detail showing utility pocket"],
    short: "A relaxed carpenter trouser in duck canvas, with a hammer loop you'll never use.",
    long: "Duck canvas that starts stiff and earns its creases. Relaxed straight leg, a utility pocket on the right thigh, and double-layer knees. Final sizes in the Archive Sale.",
    details: ["Relaxed straight leg", "Double-layer knees", "Utility pocket and hammer loop"],
    materials: "100% cotton duck canvas",
    fabric: "Cotton",
    care: "cotton",
    fit: "Relaxed",
    model: "Model is 6'1\" and wears 32",
    origin: DALLAS,
    rating: 4.6,
    reviewCount: 31,
    collections: ["archive-sale", "workwear", "gifts-under-100"],
    featured: 58,
    dropped: "2026-03-02",
    pairs: ["commerce-camp-shirt", "hollow-cardigan", "washed-cap"],
    stock: { "28": 0, "30": 1, "32": 0, "34": 2, "36": 1, "38": 0 },
  },
  // ─── Men · outerwear ───────────────────────────────────────────────
  {
    slug: "chore-jacket",
    name: "Deep Ellum Chore Jacket",
    dept: "men",
    category: "outerwear",
    price: 228,
    sizes: "alpha",
    colors: [["Black", "#1c1c1a"], ["Olive", "#4f5338", 228, "c2"]],
    alts: ["Canvas chore jacket on a model against a plain backdrop", "Chore jacket pockets and corozo buttons up close"],
    short: "A three-pocket chore coat in heavy canvas. Built to be worn every day for a decade.",
    long: "A boxy French-workwear shape in 11 oz cotton canvas: three patch pockets, a narrow collar and corozo buttons. It'll fade along every fold and look better for it.",
    details: ["Boxy fit, hip length", "Three patch pockets", "Corozo buttons, bar-tacked stress points"],
    materials: "100% cotton canvas, 11 oz",
    fabric: "Cotton",
    care: "cotton",
    fit: "Relaxed",
    model: M,
    origin: DALLAS,
    rating: 4.8,
    reviewCount: 58,
    collections: ["workwear", "bestsellers"],
    isBestseller: true,
    featured: 87,
    dropped: "2026-03-02",
    pairs: ["fisherman-knit", "selvedge-straight-jean", "washed-cap"],
  },
  {
    slug: "suede-trucker",
    name: "Suede Trucker",
    dept: "men",
    category: "outerwear",
    price: 420,
    sizes: "alpha",
    colors: [["Olive", "#4c4a33"], ["Tobacco", "#7d5636", 420, "2"]],
    alts: ["Tobacco suede jacket on a model", "Suede jacket texture and seam detail"],
    short: "A trucker jacket in goat suede, cut short with a little room in the shoulder.",
    long: "Supple goat suede from a family tannery in León, Mexico, cut into a classic trucker with pleated fronts and adjustable waist tabs. This season's run sold out in nine days — the next cut lands in November.",
    details: ["Regular fit, cropped at the hip", "Pleated front panels", "Adjustable waist tabs"],
    materials: "100% goat suede, cotton lining",
    fabric: "Suede",
    care: "suede",
    fit: "Regular",
    model: M,
    origin: "Suede from León, Mexico — cut and sewn in Dallas",
    rating: 4.9,
    reviewCount: 37,
    collections: ["bestsellers"],
    isBestseller: true,
    featured: 72,
    dropped: "2026-09-05",
    pairs: ["selvedge-straight-jean", "fisherman-knit", "felt-rancher-hat"],
    stock: { "*": 0 },
  },
  {
    slug: "mac-coat",
    name: "Trinity Mac",
    dept: "men",
    category: "outerwear",
    price: 244,
    compareAt: 348,
    sizes: "alpha",
    colors: [["Stone", "#c8b89b"]],
    alts: ["Single-breasted mac coat on a model", "Mac coat collar turned up, close detail"],
    short: "A single-breasted mac with a hidden placket — rain, wind, and Monday covered.",
    long: "Knee-length, single-breasted, with a fly-front placket, raglan sleeves and a waterproofed cotton shell. From last season; final sizes in the Archive Sale.",
    details: ["Regular fit, knee length", "Concealed placket", "Raglan sleeves, storm cuffs"],
    materials: "100% cotton with a waxed finish; cotton lining",
    fabric: "Cotton",
    care: "cotton",
    fit: "Regular",
    model: M,
    origin: DALLAS,
    rating: 4.7,
    reviewCount: 24,
    collections: ["archive-sale", "workwear"],
    featured: 63,
    dropped: "2025-10-14",
    pairs: ["field-merino-crew", "main-street-chino", "depot-weekender"],
    stock: { XS: 0, S: 0, M: 1, L: 0, XL: 1 },
  },
  // ─── Accessories · bags ────────────────────────────────────────────
  {
    slug: "plinth-leather-tote",
    name: "Plinth Leather Tote",
    dept: "unisex",
    category: "bags",
    price: 228,
    sizes: "one",
    colors: [["Tan", "#b57e4b"]],
    alts: ["Structured tan leather tote on a neutral surface", "Leather tote carried on the shoulder"],
    short: "A structured vegetable-tanned tote that fits a laptop and stands up on its own.",
    long: "Cut from a single hide of full-grain vegetable-tanned leather, with painted edges, solid brass rivets and an inner zip pocket. Unlined, so it's light — and it'll darken beautifully with use.",
    details: ["15\" W × 12\" H × 5\" D", "Fits a 14\" laptop", "Inner zip pocket, solid brass rivets"],
    materials: "Full-grain vegetable-tanned leather",
    fabric: "Leather",
    care: "leather",
    fit: "One size",
    origin: "Leather from Waco, TX — made in our Dallas studio",
    rating: 4.9,
    reviewCount: 67,
    collections: ["bestsellers", "workwear"],
    isBestseller: true,
    featured: 93,
    dropped: "2026-01-20",
    pairs: ["lone-star-trench", "bishop-poplin-shirt", "silk-square-scarf"],
  },
  {
    slug: "market-canvas-tote",
    name: "Market Canvas Tote",
    dept: "unisex",
    category: "bags",
    price: 68,
    sizes: "one",
    colors: [["Natural", "#e8e0cc"], ["Black", "#1a1918", 68, "c2"]],
    alts: ["Canvas tote bag with leather handles on a neutral background", "Canvas tote carried in hand"],
    short: "Heavy canvas with leather handles. For farmers' markets and everything else.",
    long: "18 oz cotton canvas, leather handles riveted through, and a wide flat base. Big enough for a week of groceries, quiet enough for the office.",
    details: ["16\" W × 14\" H × 6\" D", "Riveted leather handles", "Inside slip pocket"],
    materials: "18 oz cotton canvas, vegetable-tanned leather handles",
    fabric: "Canvas",
    care: "cotton",
    fit: "One size",
    origin: DALLAS,
    rating: 4.8,
    reviewCount: 90,
    collections: ["gifts-under-100", "weekend-edit", "essentials"],
    featured: 76,
    dropped: "2026-04-01",
    pairs: ["marfa-shirt-dress", "lamar-boxy-tee", "bucket-hat"],
  },
  {
    slug: "ring-crossbody",
    name: "Ring Crossbody",
    dept: "women",
    category: "bags",
    price: 188,
    sizes: "one",
    colors: [["Brown", "#5b3f2e"], ["Black", "#191817", 188, "c2"]],
    alts: ["Small black leather crossbody bag on a neutral surface", "Crossbody bag worn across the body"],
    short: "A small crossbody with a ring hardware detail. Phone, keys, card, lipstick — done.",
    long: "Smooth calf leather, a magnetic flap and our signature ring — the O from the logo — in brushed brass. The strap adjusts to wear across the body or on the shoulder.",
    details: ["8\" W × 6\" H × 2.5\" D", "Adjustable strap, 22–26\" drop", "Brushed brass ring hardware"],
    materials: "Smooth calf leather, suede lining",
    fabric: "Leather",
    care: "leather",
    fit: "One size",
    origin: DALLAS,
    rating: 4.8,
    reviewCount: 48,
    collections: ["new-in", "gifts-under-100"],
    isNew: true,
    featured: 89,
    dropped: "2026-09-19",
    pairs: ["calle-slip-dress", "ellum-barrel-jean", "mesa-cropped-jacket"],
  },
  {
    slug: "depot-weekender",
    name: "Depot Weekender",
    dept: "unisex",
    category: "bags",
    price: 208,
    compareAt: 298,
    sizes: "one",
    colors: [["Black", "#1a1918"], ["Cognac", "#8a5330", 208, "2"]],
    alts: ["Leather and canvas weekender bag on a neutral background", "Weekender bag carried by its handles"],
    short: "A two-night duffle in full-grain leather. Fits under a plane seat.",
    long: "Supple full-grain leather in black or cognac, a full-length brass zip, rolled handles and a detachable shoulder strap. Sized for carry-on. Final units of last year's run in the Archive Sale.",
    details: ["20\" W × 11\" H × 9\" D", "Carry-on size", "Detachable shoulder strap"],
    materials: "Full-grain leather, cotton twill lining, brass hardware",
    fabric: "Leather",
    care: "leather",
    fit: "One size",
    origin: DALLAS,
    rating: 4.8,
    reviewCount: 29,
    collections: ["archive-sale"],
    featured: 61,
    dropped: "2025-11-20",
    pairs: ["akard-overshirt", "mac-coat", "washed-cap"],
    stock: { "One size": 2 },
  },
  // ─── Accessories · belts, scarves, hats ───────────────────────────
  {
    slug: "bridle-belt",
    name: "Bridle Belt",
    dept: "unisex",
    category: "accessories",
    price: 78,
    sizes: "belt",
    colors: [["Tan", "#b0753f"], ["Black", "#1a1918", 78, "c2"]],
    alts: ["Brown bridle leather belt with a brass buckle", "Leather belt worn with trousers, buckle close-up"],
    short: "A 1.25\" bridle leather belt with a solid brass roller buckle.",
    long: "English-style bridle leather — dense, waxed and built to outlast the trousers you wear it with. Edges hand-burnished, buckle held with screws so it can be swapped.",
    details: ["1.25\" wide", "Solid brass buckle, screw fastening", "S fits 28–30, M 32–34, L 36–38"],
    materials: "Bridle leather, solid brass",
    fabric: "Leather",
    care: "leather",
    fit: "One size",
    origin: DALLAS,
    rating: 4.9,
    reviewCount: 85,
    collections: ["gifts-under-100", "essentials"],
    featured: 69,
    dropped: "2026-01-20",
    pairs: ["oak-cliff-wide-trouser", "selvedge-straight-jean", "ervay-oxford"],
  },
  {
    slug: "woven-belt",
    name: "Woven Belt",
    dept: "unisex",
    category: "accessories",
    price: 58,
    sizes: "belt",
    colors: [["Brown", "#6b4428"]],
    alts: ["Braided woven leather belt coiled on a neutral surface", "Woven belt worn through denim belt loops"],
    short: "A braided leather belt with infinite holes. Summer's belt.",
    long: "Hand-braided strips of vegetable-tanned leather, so the prong goes wherever you need it. Antiqued brass buckle.",
    details: ["1\" wide", "Fits any hole — it's braided", "Antiqued brass buckle"],
    materials: "Vegetable-tanned leather, brass",
    fabric: "Leather",
    care: "leather",
    fit: "One size",
    origin: "Braided in Oaxaca, finished in Dallas",
    rating: 4.7,
    reviewCount: 42,
    collections: ["gifts-under-100", "weekend-edit"],
    featured: 57,
    dropped: "2026-04-01",
    pairs: ["marfa-shirt-dress", "ellum-barrel-jean", "commerce-camp-shirt"],
  },
  {
    slug: "silk-square-scarf",
    name: "Bishop Silk Square",
    dept: "unisex",
    category: "accessories",
    price: 62,
    compareAt: 88,
    sizes: "one",
    colors: [["Ink", "#1f2433"], ["Clay print", "#b6694a", 62, "2"]],
    alts: ["Printed silk square scarf folded on a neutral surface", "Silk scarf tied at the neck"],
    short: "A 27\" silk twill square in ink navy with a hand-drawn border — or our clay print.",
    long: "Silk twill with a hand-rolled hem, in deep ink with a hand-drawn border, or a clay-and-cream print drawn from the tiles on Bishop Ave. Wear it at the neck, on a bag handle, or in your hair. Last of the first edition in the Archive Sale.",
    details: ["27\" × 27\"", "Hand-rolled hem", "First edition of 200"],
    materials: "100% silk twill",
    fabric: "Silk",
    care: "silk",
    fit: "One size",
    origin: "Printed in Como, Italy — hemmed in Dallas",
    rating: 4.8,
    reviewCount: 36,
    collections: ["archive-sale", "gifts-under-100"],
    featured: 59,
    dropped: "2025-12-01",
    pairs: ["plinth-leather-tote", "calle-slip-dress", "bishop-poplin-shirt"],
    stock: { "One size": 3 },
  },
  {
    slug: "mohair-scarf",
    name: "Norther Knit Scarf",
    dept: "unisex",
    category: "accessories",
    price: 98,
    sizes: "one",
    colors: [["Taupe", "#a39784"]],
    alts: ["Brushed mohair scarf in rust folded on a neutral surface", "Mohair scarf wrapped around the neck"],
    short: "A chunky, cloud-soft knit scarf for when the norther blows in.",
    long: "Hand-loomed in a loose, chunky stitch from baby alpaca and wool — light for its size and warmer than it looks. Named for the Texas cold fronts that drop the temperature thirty degrees in an hour.",
    details: ["12\" × 70\"", "Chunky hand-loomed knit", "Wear long or doubled"],
    materials: "60% baby alpaca, 40% wool",
    fabric: "Knit",
    care: "knit",
    fit: "One size",
    origin: "Woven in Scotland — finished in Dallas",
    rating: 4.9,
    reviewCount: 31,
    collections: ["new-in", "gifts-under-100"],
    isNew: true,
    featured: 78,
    dropped: "2026-10-01",
    pairs: ["pecan-wool-coat", "mac-coat", "rib-beanie"],
  },
  {
    slug: "felt-rancher-hat",
    name: "Rancher Felt Hat",
    dept: "unisex",
    category: "accessories",
    price: 128,
    sizes: "hat",
    colors: [["Black", "#1b1a19"]],
    alts: ["Wide-brim wool felt hat on a neutral backdrop", "Felt hat worn, brim shading the face"],
    short: "A flat-brim wool felt hat. Not a costume — just good shade.",
    long: "Water-resistant wool felt with a 3.25\" flat brim and a teardrop crown, finished with a grosgrain band. Sweatband is soft leather.",
    details: ["3.25\" brim", "Teardrop crown", "Leather sweatband"],
    materials: "100% wool felt, grosgrain band, leather sweatband",
    fabric: "Felt",
    care: "felt",
    fit: "One size",
    origin: "Blocked in Garland, TX",
    rating: 4.7,
    reviewCount: 27,
    collections: ["weekend-edit"],
    featured: 67,
    dropped: "2026-05-02",
    pairs: ["marfa-shirt-dress", "suede-trucker", "woven-belt"],
  },
  {
    slug: "washed-cap",
    name: "Washed Cap",
    dept: "unisex",
    category: "accessories",
    price: 38,
    sizes: "one",
    colors: [["Grey", "#8e8b86"], ["Khaki", "#b7a27c", 38, "2"]],
    alts: ["Washed cotton six-panel cap on a neutral surface", "Washed cap worn with an overshirt"],
    short: "A garment-washed six-panel cap with a brass slider. No logo, on purpose.",
    long: "Soft cotton twill washed for a broken-in feel on day one, an unstructured crown and a curved brim. The only branding is a small woven tab inside.",
    details: ["Unstructured six-panel", "Brass slider strap", "One size fits most"],
    materials: "100% cotton twill",
    fabric: "Cotton",
    care: "cotton",
    fit: "One size",
    origin: DALLAS,
    rating: 4.6,
    reviewCount: 74,
    collections: ["gifts-under-100", "essentials"],
    featured: 54,
    dropped: "2026-03-10",
    pairs: ["chore-jacket", "elm-rib-tank", "drill-work-trouser"],
  },
  {
    slug: "bucket-hat",
    name: "Canvas Bucket Hat",
    dept: "unisex",
    category: "accessories",
    price: 34,
    compareAt: 48,
    sizes: "hat",
    colors: [["Black", "#1c1b19"], ["Tan", "#c4a876", 34, "c2"]],
    alts: ["Canvas bucket hat on a neutral background", "Bucket hat worn outdoors in the sun"],
    short: "A soft canvas bucket hat with a short brim. Folds into a pocket.",
    long: "Washed cotton canvas with a stitched brim that holds its shape and two brass eyelets for airflow. Final sizes in the Archive Sale.",
    details: ["2\" brim", "Brass eyelets", "Packable"],
    materials: "100% cotton canvas",
    fabric: "Cotton",
    care: "cotton",
    fit: "One size",
    origin: DALLAS,
    rating: 4.5,
    reviewCount: 40,
    collections: ["archive-sale", "gifts-under-100", "weekend-edit"],
    featured: 52,
    dropped: "2026-04-22",
    pairs: ["commerce-camp-shirt", "lamar-boxy-tee", "market-canvas-tote"],
    stock: { "S/M": 0, "L/XL": 2 },
  },
  {
    slug: "rib-beanie",
    name: "Rib Beanie",
    dept: "unisex",
    category: "accessories",
    price: 42,
    sizes: "one",
    colors: [["Camel", "#b8875a"], ["Grey", "#9b9893", 42, "2"]],
    alts: ["Ribbed knit beanie on a neutral surface", "Ribbed beanie worn with a turned-up cuff"],
    short: "A deep-cuff rib beanie in soft merino. Sits above the ear or covers it.",
    long: "Knitted in a fine 2×2 rib with a deep turn-up so you can wear it slouched or tight. Merino, so it doesn't itch and doesn't overheat indoors.",
    details: ["Deep turn-up cuff", "Fine 2×2 rib", "One size"],
    materials: "100% merino wool",
    fabric: "Knit",
    care: "knit",
    fit: "One size",
    origin: "Knitted in Los Angeles, finished in Dallas",
    rating: 4.8,
    reviewCount: 66,
    collections: ["new-in", "gifts-under-100"],
    isNew: true,
    featured: 56,
    dropped: "2026-10-01",
    pairs: ["akard-overshirt", "fisherman-knit", "mohair-scarf"],
  },
];

/* ───────────────────────────── expansion ───────────────────────────── */

function hash(s: string) {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

const skuPrefix: Record<CategorySlug, string> = {
  dresses: "DR",
  tops: "TP",
  knitwear: "KN",
  trousers: "TR",
  outerwear: "OW",
  bags: "BG",
  accessories: "AC",
};

function build(d: Def, index: number): Product {
  const sizes = SIZES[d.sizes];
  const sizeSystem: SizeSystem = d.sizes === "one" ? "one" : d.sizes === "waist" || d.sizes === "wwaist" ? "waist" : "alpha";
  const img = (n: string) => `/images/products/${d.slug}-${n}.jpg`;

  const colors: Colorway[] = d.colors.map(([name, hex, price, photo], i) => ({
    name,
    hex,
    image: i === 0 ? img("1") : photo ? img(photo) : img("1"),
    price: price && price !== d.price ? price : undefined,
  }));

  const variants: Variant[] = [];
  colors.forEach((c, ci) => {
    sizes.forEach((size) => {
      const sku = `OR-${skuPrefix[d.category]}${String(index + 1).padStart(2, "0")}-${c.name.replace(/[^A-Za-z]/g, "").slice(0, 3).toUpperCase()}-${size.replace(/[^A-Za-z0-9]/g, "")}`;
      let stock = 2 + (hash(sku) % 11);
      if (d.stock) {
        if ("*" in d.stock) stock = d.stock["*"];
        else if (ci === 0 && size in d.stock) stock = d.stock[size];
        else if (d.compareAt) stock = hash(sku) % 3; // sale pieces: second colour is thin too
      }
      variants.push({
        id: sku.toLowerCase(),
        sku,
        color: c.name,
        size,
        price: c.price ?? d.price,
        compareAt: d.compareAt,
        stock,
      });
    });
  });

  const pool = reviewPool[d.category];
  const start = hash(d.slug) % pool.length;
  const n = 3 + (hash(d.slug + "n") % 2);
  const reviews: Review[] = Array.from({ length: Math.min(n, pool.length) }, (_, k) => {
    const r = pool[(start + k) % pool.length];
    return { ...r, id: `${d.slug}-r${k}` };
  });
  const fitScore = d.fitScore ?? reviews.reduce((a, r) => a + r.fit, 0) / reviews.length;

  const collections = new Set<CollectionSlug>(d.collections ?? []);
  if (d.price < 100 || (d.compareAt && d.price < 100)) collections.add("gifts-under-100");
  if (d.compareAt) collections.add("archive-sale");
  if (d.isNew) collections.add("new-in");
  if (d.isBestseller) collections.add("bestsellers");

  return {
    slug: d.slug,
    name: d.name,
    dept: d.dept,
    category: d.category,
    price: d.price,
    compareAt: d.compareAt,
    sizeSystem,
    sizes,
    colors,
    variants,
    images: [
      { src: img("1"), alt: productImageMeta[`${d.slug}-1`]?.alt ?? d.alts[0], focal: d.focal?.[0] ?? productImageMeta[`${d.slug}-1`]?.focal },
      { src: img("2"), alt: productImageMeta[`${d.slug}-2`]?.alt ?? d.alts[1], focal: d.focal?.[1] ?? productImageMeta[`${d.slug}-2`]?.focal },
    ],
    short: d.short,
    long: d.long,
    details: d.details,
    materials: d.materials,
    care: [...CARE[d.care]],
    origin: d.origin ?? DALLAS,
    model: d.model,
    fabric: d.fabric,
    fit: d.fit,
    fitScore: Math.max(-1, Math.min(1, fitScore)),
    rating: d.rating,
    reviewCount: d.reviewCount,
    reviews,
    collections: [...collections],
    isNew: d.isNew,
    isBestseller: d.isBestseller,
    featured: d.featured,
    dropped: d.dropped,
    pairs: d.pairs,
  };
}

export const products: Product[] = defs.map(build);

export const productBySlug = new Map(products.map((p) => [p.slug, p]));
export const variantById = new Map(products.flatMap((p) => p.variants.map((v) => [v.id, { product: p, variant: v }] as const)));

export const departments = [
  { slug: "women", name: "Women" },
  { slug: "men", name: "Men" },
  { slug: "unisex", name: "Unisex" },
] as const;
